Repository kleveross/klever-model-registry, pull requests merged in 2020-07, with the labels that each got.

#30 feat: Add modeljob apis
  go.sum
  pkg/common/consts.go
  pkg/registry/server/event/controller.go
  pkg/registry/server/event/route.go
  pkg/registry/server/harbor/handler.go
  pkg/registry/server/modeljob/controller.go
  pkg/registry/server/modeljob/route.go
  pkg/registry/server/modeljob/util.go
  pkg/registry/server/server.go
  pkg/util/utils.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#31 fix(operator): Fix modeljob status
  go.mod
  go.sum
  pkg/apis/modeljob/v1alpha1/modeljob_types.go
  pkg/controllers/reconcile.go
  pkg/controllers/utils.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#46 feat: Replace apis with api of url prefix
  pkg/registry/apis/api.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#50 feat: Add modeljob operator unit tests
  .travis.yml
  README.md
  pkg/controllers/initialization.go
  pkg/controllers/modeljob_controller_test.go
  pkg/controllers/reconcile.go
  pkg/controllers/reconcile_test.go
  pkg/controllers/suite_test.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
  testutil/testutil.go
Labels: approved, lgtm, release-note-none, size/XL

#51 feat: Add badge for chinese README
  README_zh.md
Labels: approved, release-note-none, size/XS

#56 fix(env): add domain ip env and modify run shell
  manifests/klever-modeljob-operator/templates/deployment.yaml
  manifests/klever-modeljob-operator/values.yaml
  scripts/shell/run.sh
Labels: approved, lgtm, release-note-none, size/XS

#54 feat: Refactor api
  pkg/registry/apis/api.go
  pkg/registry/apis/v1alpha1/descriptors/harbor.go
  pkg/registry/harbor/harbor.go
Labels: approved, lgtm, release-note-none, size/L

#59 chore(*): adjust the config of the nirvana server
  Makefile
  cmd/klever-model-registry/main.go
  nirvana.yaml
  pkg/registry/apis/api.go
  pkg/registry/apis/v1alpha1/descriptors/descriptor.go
  pkg/registry/apis/v1alpha1/descriptors/modeljob.go
  pkg/registry/filters/filters.go
  pkg/registry/modifiers/modifiers.go
Labels: approved, lgtm, release-note-none, size/M

#60 chore(Makefile): tweak for GOFLAGS config
  Makefile
  docs/api/api.v1alpha1.json
Labels: approved, lgtm, release-note-none, size/M

#57 fix(api): add namespace in registry api
  pkg/registry/apis/v1alpha1/descriptors/modeljob.go
  pkg/registry/event/event_test.go
  pkg/registry/modeljob/modeljob.go
  pkg/registry/modeljob/modeljob_test.go
Labels: approved, lgtm, release-note-none, size/M

#62 feat: Remove config dir
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/modeljobs.kleveross.io_modeljobs.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_modeljobs.yaml
  config/crd/patches/webhook_in_modeljobs.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/manager/model-registry.yaml
  config/manager/modeljob-operator.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/modeljob_editor_role.yaml
  config/rbac/modeljob_viewer_role.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/samples/modeljobs_v1alpha1_caffe2_extract.yaml
  config/samples/modeljobs_v1alpha1_caffe_convert.yaml
  config/samples/modeljobs_v1alpha1_caffe_extract.yaml
  config/samples/modeljobs_v1alpha1_graphdef_extract.yaml
  config/samples/modeljobs_v1alpha1_h5_convert.yaml
  config/samples/modeljobs_v1alpha1_h5_extract.yaml
  config/samples/modeljobs_v1alpha1_mxnet_convert.yaml
  config/samples/modeljobs_v1alpha1_mxnet_extract.yaml
  config/samples/modeljobs_v1alpha1_onnx_extract.yaml
  config/samples/modeljobs_v1alpha1_pmml_extract.yaml
  config/samples/modeljobs_v1alpha1_savedmodel_extract.yaml
  config/samples/modeljobs_v1alpha1_torchscript_extract.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
Labels: approved, lgtm, release-note-none, size/XL

#64 feat(deploy): Support deploy Harbor by helm
  README.md
  README_zh.md
  hack/boilerplate.go.txt
  manifests/examples/modeljobs_v1alpha1_caffe2_extract.yaml
  manifests/examples/modeljobs_v1alpha1_caffe_convert.yaml
  manifests/examples/modeljobs_v1alpha1_caffe_extract.yaml
  manifests/examples/modeljobs_v1alpha1_graphdef_extract.yaml
  manifests/examples/modeljobs_v1alpha1_h5_convert.yaml
  manifests/examples/modeljobs_v1alpha1_h5_extract.yaml
  manifests/examples/modeljobs_v1alpha1_mxnet_convert.yaml
  manifests/examples/modeljobs_v1alpha1_mxnet_extract.yaml
  manifests/examples/modeljobs_v1alpha1_onnx_extract.yaml
  manifests/examples/modeljobs_v1alpha1_pmml_extract.yaml
  manifests/examples/modeljobs_v1alpha1_savedmodel_extract.yaml
  manifests/examples/modeljobs_v1alpha1_torchscript_extract.yaml
  manifests/klever-model-registry/templates/deployment.yaml
  manifests/klever-model-registry/templates/service.yaml
  manifests/klever-model-registry/values.yaml
  manifests/klever-modeljob-operator/templates/cluster-role-binding.yaml
  manifests/klever-modeljob-operator/templates/deployment.yaml
  manifests/klever-modeljob-operator/templates/preset-image-configmap.yaml
  manifests/klever-modeljob-operator/templates/secret.yaml
  manifests/klever-modeljob-operator/values.yaml
  scripts/shell/run.sh
Labels: approved, lgtm, release-note-none, size/L

#66 feat(*): Support more params when upload model
  pkg/common/consts.go
  pkg/registry/client/client.go
  pkg/registry/models/files.go
  pkg/registry/models/types.go
  pkg/registry/models/util.go
  pkg/registry/models/util_test.go
Labels: approved, lgtm
