Repository kleveross/klever-model-registry, pull requests merged in 2020-09, with the labels that each got.

#88 fix: Set modeljob's job BackoffLimit 0
  pkg/controllers/utils.go
Labels: approved, lgtm, release-note-none, size/XS

#91 feat: Auto create extract modeljob when ormb push
  cmd/model-registry/main.go
  go.sum
  pkg/registry/apis/api.go
  pkg/registry/apis/v1alpha1/descriptors/harbor.go
  pkg/registry/harbor/artifacts.go
  pkg/registry/harbor/harbor.go
Labels: approved, lgtm, release-note-none, size/L

#93 fix: Fix ormb can not push bug
  README.md
  README_zh.md
  manifests/model-registry/templates/deployment.yaml
  manifests/model-registry/values.yaml
  pkg/registry/apis/v1alpha1/descriptors/harbor.go
  pkg/registry/harbor/harbor.go
Labels: approved, lgtm, release-note-none, size/M

#94 fix(model): add project parameter in model upload and download
  pkg/registry/apis/v1alpha1/descriptors/model.go
  pkg/registry/models/files.go
  pkg/registry/models/types.go
  pkg/registry/models/util.go
  pkg/util/utils.go
Labels: approved, lgtm, release-note-none, size/M

#98 fix(api): change log to logs by following the RESTFul specification
  pkg/registry/apis/v1alpha1/descriptors/log.go
Labels: approved, lgtm, release-note-none, size/XS

#97 chore(docs): add model registry docs and open-source license
  CONTRIBUTING.md
  LICENSE
  docs/README.md
  docs/developers/api.md
  docs/docs_zh/README.md
  docs/docs_zh/developers/api.md
Labels: approved, lgtm, release-note-none, size/XL

#96 feat: Add more e2e test cases
  .gitignore
  go.mod
  pkg/registry/models/files.go
  pkg/registry/models/types.go
  pkg/registry/models/util.go
  testutil/integration/models/model.zip
  testutil/integration/registry_test.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L

#101 fix(api): fulfill api information and add some comments
  pkg/registry/apis/v1alpha1/descriptors/event.go
  pkg/registry/apis/v1alpha1/descriptors/harbor.go
  pkg/registry/apis/v1alpha1/descriptors/log.go
  pkg/registry/apis/v1alpha1/descriptors/modeljob.go
  pkg/registry/apis/v1alpha1/descriptors/serving.go
Labels: approved, lgtm, release-note-none, size/S

#105 chore(docs): add model serving doc, fix the api doc link and mv dockerfile to build folder
  build/serving/openscoring/Dockerfile
  build/serving/tensorrt/Dockerfile
  docs/README.md
  docs/docs_zh/README.md
  scripts/serving/openscoring/application.conf
  scripts/serving/tensorrt/requirements.txt
Labels: approved, lgtm, release-note-none, size/M

#106 feat: Set reverse proxy response content-type to application/json
  .gitignore
  pkg/registry/harbor/harbor.go
  testutil/integration/registry_test.go
Labels: approved, lgtm, release-note-none, size/S

#95 feat: Support gRPC and HTTP protocols
  pkg/registry/serving/composer.go
  pkg/registry/serving/composer_test.go
Labels: approved, lgtm, release-note-none, size/M

#110 fix: Fix upload model if model zip is model.zip
  pkg/registry/models/util.go
Labels: approved, lgtm, release-note-none, size/S

#109 feat: Support paging for modeljob and serving
  go.mod
  go.sum
  pkg/registry/apis/v1alpha1/descriptors/modeljob.go
  pkg/registry/apis/v1alpha1/descriptors/serving.go
  pkg/registry/modeljob/modeljob.go
  pkg/registry/modeljob/modeljob_test.go
  pkg/registry/paging/paging.go
  pkg/registry/serving/serving.go
  vendor/github.com/caicloud/nirvana/operators/validator/tags.go
  vendor/github.com/caicloud/nirvana/operators/validator/validator.go
  vendor/github.com/go-playground/locales/.gitignore
  vendor/github.com/go-playground/locales/LICENSE
  vendor/github.com/go-playground/locales/README.md
  vendor/github.com/go-playground/locales/currency/currency.go
  vendor/github.com/go-playground/locales/logo.png
  vendor/github.com/go-playground/locales/rules.go
  vendor/github.com/go-playground/universal-translator/.gitignore
  vendor/github.com/go-playground/universal-translator/LICENSE
  vendor/github.com/go-playground/universal-translator/README.md
  vendor/github.com/go-playground/universal-translator/errors.go
  vendor/github.com/go-playground/universal-translator/import_export.go
  vendor/github.com/go-playground/universal-translator/logo.png
  vendor/github.com/go-playground/universal-translator/translator.go
  vendor/github.com/go-playground/universal-translator/universal_translator.go
  vendor/gopkg.in/go-playground/validator.v9/.gitignore
  vendor/gopkg.in/go-playground/validator.v9/LICENSE
  vendor/gopkg.in/go-playground/validator.v9/Makefile
  vendor/gopkg.in/go-playground/validator.v9/README.md
  vendor/gopkg.in/go-playground/validator.v9/baked_in.go
  vendor/gopkg.in/go-playground/validator.v9/cache.go
  vendor/gopkg.in/go-playground/validator.v9/doc.go
  vendor/gopkg.in/go-playground/validator.v9/errors.go
  vendor/gopkg.in/go-playground/validator.v9/field_level.go
  vendor/gopkg.in/go-playground/validator.v9/logo.png
  vendor/gopkg.in/go-playground/validator.v9/regexes.go
  vendor/gopkg.in/go-playground/validator.v9/struct_level.go
  vendor/gopkg.in/go-playground/validator.v9/translations.go
  vendor/gopkg.in/go-playground/validator.v9/util.go
  vendor/gopkg.in/go-playground/validator.v9/validator.go
  vendor/gopkg.in/go-playground/validator.v9/validator_instance.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/XXL

#111 fix: Fix import bug
  pkg/registry/modeljob/modeljob_test.go
Labels: approved, lgtm, release-note-none, size/XS

#112 feat: Update ormb version in Dockerfile
  build/convert/caffemodel_to_netdef/Dockerfile
  build/convert/h5_to_savedmodel/Dockerfile
  build/convert/mxnetparams_to_onnx/Dockerfile
  build/extract/caffe/Dockerfile
  build/extract/caffe2/Dockerfile
  build/extract/graphdef/Dockerfile
  build/extract/h5/Dockerfile
  build/extract/mxnetparams/Dockerfile
  build/extract/onnx/Dockerfile
  build/extract/pmml/Dockerfile
  build/extract/savedmodel/Dockerfile
  build/extract/tensorrt/Dockerfile
  build/extract/torchscript/Dockerfile
Labels: approved, lgtm, release-note-none, size/M

#114 feat: Auto extract model when upload model in the UI
  pkg/registry/harbor/artifacts.go
  pkg/registry/modeljob/util.go
  pkg/registry/models/files.go
  testutil/integration/registry_test.go
Labels: approved, lgtm, release-note-none, size/M

#115 feat: Support auto extract after convert
  manifests/modeljob-operator/templates/deployment.yaml
  manifests/modeljob-operator/values.yaml
  pkg/controllers/consts.go
  pkg/controllers/modeljob_controller_test.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
Labels: approved, lgtm, release-note-none, size/M

#116 chore(docs): add CONTRIBUTING doc
  CONTRIBUTING.md
  README.md
  README_zh.md
  docs/developers/api.md
  docs/docs_zh/developers/api.md
Labels: approved, lgtm, release-note-none, size/L

#117 fix: Fix mxnet Dockerfile
  build/extract/mxnetparams/Dockerfile
Labels: approved, lgtm, release-note-none, size/XS

#118 misc: Update PROJECT
  PROJECT
Labels: approved, lgtm, release-note-none, size/XS

#121 feat(controller): Support set SchedulerName
  manifests/modeljob-operator/templates/deployment.yaml
  manifests/modeljob-operator/values.yaml
  pkg/controllers/consts.go
  pkg/controllers/utils.go
Labels: approved, lgtm, release-note-none, size/S

#122 feat(docs): Add seldon core install docs
  README.md
  README_zh.md
  docs/installation/installation.md
  docs/installation/installation_zh.md
Labels: approved, lgtm, release-note-none, size/L

#120 Feat(comparison): add model comparison from ormb metadata
  pkg/registry/apis/v1alpha1/descriptors/comparison.go
  pkg/registry/comparison/comparison.go
  pkg/registry/comparison/types.go
  pkg/registry/harbor/artifacts.go
Labels: approved, lgtm, release-note-none, size/L

#123 Chore(owners): add FogDong
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#119 feat: Add ModelJob E2E Test
  .github/workflows/e2e.yml
  pkg/registry/serving/serving.go
  testutil/integration/model_test.go
  testutil/integration/serving_test.go
Labels: approved, lgtm, release-note-none, size/L

#124 Feat(test): add comparison test
  pkg/registry/apis/v1alpha1/descriptors/harbor.go
  pkg/registry/comparison/comparison.go
  pkg/registry/comparison/comparison_test.go
  pkg/registry/harbor/artifacts.go
  pkg/registry/harbor/harbor.go
  pkg/registry/harbor/harbor_fake.go
Labels: approved, lgtm, release-note-none, size/L

#125 fix(docs): Update installation manual
  README.md
  README_zh.md
  docs/docs_zh/installation.md
  docs/installation.md
Labels: approved, lgtm, release-note-none, size/XS

#129 fix: Fix serving model dir structure
  pkg/registry/harbor/artifacts.go
  pkg/registry/modeljob/util.go
  pkg/registry/models/files.go
  pkg/registry/serving/composer.go
  scripts/serving/wrapper/entrypoint.sh
  scripts/serving/wrapper/openscoring.sh
  scripts/serving/wrapper/preprocessor.py
  scripts/serving/wrapper/utils/get_model.py
Labels: approved, lgtm, release-note-none, size/M

#130 Feat(serving): add sklearn and xgboost simple serving
  build/serving/mlserver/Dockerfile
  build/serving/openscoring/Dockerfile
  build/serving/tensorrt/Dockerfile
  manifests/model-registry/templates/deployment.yaml
  manifests/model-registry/values.yaml
  pkg/apis/modeljob/v1alpha1/modeljob_types.go
  pkg/registry/serving/composer.go
  scripts/serving/mlserver/entrypoint.sh
  scripts/serving/mlserver/mlserver/__init__.py
  scripts/serving/mlserver/mlserver/cli/__init__.py
  scripts/serving/mlserver/mlserver/cli/build.py
  scripts/serving/mlserver/mlserver/cli/main.py
  scripts/serving/mlserver/mlserver/cli/serve.py
  scripts/serving/mlserver/mlserver/errors.py
  scripts/serving/mlserver/mlserver/grpc/__init__.py
  scripts/serving/mlserver/mlserver/grpc/converters.py
  scripts/serving/mlserver/mlserver/grpc/dataplane_pb2.py
  scripts/serving/mlserver/mlserver/grpc/dataplane_pb2.pyi
  scripts/serving/mlserver/mlserver/grpc/dataplane_pb2_grpc.py
  scripts/serving/mlserver/mlserver/grpc/server.py
  scripts/serving/mlserver/mlserver/grpc/servicers.py
  scripts/serving/mlserver/mlserver/handlers.py
  scripts/serving/mlserver/mlserver/model.py
  scripts/serving/mlserver/mlserver/models/__init__.py
  scripts/serving/mlserver/mlserver/models/sklearn.py
  scripts/serving/mlserver/mlserver/models/xgboost.py
  scripts/serving/mlserver/mlserver/repository.py
  scripts/serving/mlserver/mlserver/rest/__init__.py
  scripts/serving/mlserver/mlserver/rest/app.py
  scripts/serving/mlserver/mlserver/rest/endpoints.py
  scripts/serving/mlserver/mlserver/rest/errors.py
  scripts/serving/mlserver/mlserver/rest/requests.py
  scripts/serving/mlserver/mlserver/rest/server.py
  scripts/serving/mlserver/mlserver/rest/utils.py
  scripts/serving/mlserver/mlserver/server.py
  scripts/serving/mlserver/mlserver/settings.py
  scripts/serving/mlserver/mlserver/types.py
  scripts/serving/mlserver/mlserver/version.py
  scripts/serving/mlserver/setup.py
  scripts/serving/openscoring/openscoring.sh
  scripts/serving/tensorrt/entrypoint.sh
  scripts/serving/wrapper/preprocessor.py
  scripts/serving/wrapper/requirements.txt
  scripts/serving/wrapper/utils/help_functions.py
  scripts/serving/wrapper/utils/model_formatter.py
Labels: approved, lgtm, release-note-none, size/XXL

#132 feat: Support set model initializer container resource
  manifests/model-registry/templates/deployment.yaml
  pkg/registry/serving/composer.go
  pkg/registry/serving/composer_test.go
Labels: approved, lgtm, release-note-none, size/M

#133 [fix] Fix the test coverage
  .github/workflows/main.yml
Labels: approved, lgtm, release-note-none, size/XS

#134 Fix(build): fix serving dockerfile
  build/serving/mlserver/Dockerfile
  build/serving/openscoring/Dockerfile
  scripts/serving/mlserver/mlserver/__init__.py
  scripts/serving/mlserver/mlserver/cli/__init__.py
  scripts/serving/mlserver/mlserver/cli/build.py
  scripts/serving/mlserver/mlserver/cli/main.py
  scripts/serving/mlserver/mlserver/cli/serve.py
  scripts/serving/mlserver/mlserver/errors.py
  scripts/serving/mlserver/mlserver/grpc/__init__.py
  scripts/serving/mlserver/mlserver/grpc/converters.py
  scripts/serving/mlserver/mlserver/grpc/dataplane_pb2.py
  scripts/serving/mlserver/mlserver/grpc/dataplane_pb2.pyi
  scripts/serving/mlserver/mlserver/grpc/dataplane_pb2_grpc.py
  scripts/serving/mlserver/mlserver/grpc/server.py
  scripts/serving/mlserver/mlserver/grpc/servicers.py
  scripts/serving/mlserver/mlserver/handlers.py
  scripts/serving/mlserver/mlserver/model.py
  scripts/serving/mlserver/mlserver/models/__init__.py
  scripts/serving/mlserver/mlserver/models/sklearn.py
  scripts/serving/mlserver/mlserver/models/xgboost.py
  scripts/serving/mlserver/mlserver/repository.py
  scripts/serving/mlserver/mlserver/rest/__init__.py
  scripts/serving/mlserver/mlserver/rest/app.py
  scripts/serving/mlserver/mlserver/rest/endpoints.py
  scripts/serving/mlserver/mlserver/rest/errors.py
  scripts/serving/mlserver/mlserver/rest/requests.py
  scripts/serving/mlserver/mlserver/rest/server.py
  scripts/serving/mlserver/mlserver/rest/utils.py
  scripts/serving/mlserver/mlserver/server.py
  scripts/serving/mlserver/mlserver/settings.py
  scripts/serving/mlserver/mlserver/types.py
  scripts/serving/mlserver/mlserver/version.py
  scripts/serving/mlserver/setup.py
  scripts/serving/openscoring/entrypoint.sh
Labels: approved, lgtm, release-note-none, size/XXL

#135 fix: Fix GPU schedule
  pkg/registry/serving/composer.go
Labels: approved, lgtm, release-note-none, size/M

#136 feat(installation): Update installation
  Makefile
  docs/docs_zh/installation.md
  docs/installation.md
  manifests/model-registry/templates/deployment.yaml
  manifests/model-registry/templates/service.yaml
  manifests/model-registry/values.yaml
  manifests/modeljob-operator/templates/preset-image-configmap.yaml
  manifests/modeljob-operator/templates/secret.yaml
  manifests/modeljob-operator/values.yaml
  scripts/installation/install.sh
Labels: approved, lgtm, release-note-none, size/L

#137 feat(docs): Update Install docs
  README.md
  README_zh.md
  docs/docs_zh/installation.md
  docs/installation.md
  scripts/installation/install.sh
Labels: approved, lgtm, release-note-none, size/M

#138 feat: Add more unit tests
  pkg/registry/comparison/comparison.go
  pkg/registry/comparison/comparison_test.go
Labels: approved, lgtm, release-note-none, size/L

#141 fix(controllers): Remove controller global init
  pkg/common/consts.go
  pkg/controllers/initialization.go
  pkg/controllers/modeljob_controller_test.go
  pkg/controllers/utils_test.go
  pkg/registry/event/event_test.go
  pkg/registry/modeljob/modeljob.go
  pkg/registry/modeljob/modeljob_test.go
  pkg/registry/modeljob/util.go
  pkg/registry/modeljob/util_test.go
  testutil/integration/model_test.go
Labels: approved, lgtm, release-note-none, size/M

#142 fix(serving): Update serving resources
  cmd/model-registry/main.go
  pkg/registry/serving/composer.go
  pkg/registry/serving/composer_test.go
  testutil/integration/serving_test.go
Labels: approved, lgtm, release-note-none, size/L

#143 fix(e2e): Fix e2e tests
  pkg/registry/serving/composer_test.go
Labels: approved, lgtm, release-note-none, size/M

#144 feat(ci): Add publish action
  .github/workflows/publish.yml
Labels: release-note-none, size/S

#146 feat(action): Add publish action
  .github/workflows/publish.yml
  build/extract/caffe/Dockerfile
  build/extract/pmml/Dockerfile
  build/serving/openscoring/Dockerfile
  manifests/model-registry/Chart.yaml
  manifests/model-registry/values.yaml
  manifests/modeljob-operator/Chart.yaml
  manifests/modeljob-operator/templates/preset-image-configmap.yaml
Labels: approved, lgtm, release-note-none, size/L

#147 fix(action): Fix docker image version in publish action
  .github/workflows/publish.yml
  build/extract/caffe/Dockerfile
  manifests/modeljob-operator/templates/preset-image-configmap.yaml
Labels: approved, lgtm, release-note-none, size/M

#148 fix(action): Fix public action
  .github/workflows/publish.yml
Labels: approved, lgtm, release-note-none, size/XS

#151 fix: Fix dockerfile
  build/extract/caffe2/Dockerfile
  build/extract/mxnetparams/Dockerfile
  build/extract/torchscript/Dockerfile
Labels: approved, lgtm, release-note-none, size/XS

#152 fix: Fix github action
  build/extract/caffe2/Dockerfile
Labels: release-note-none

#153 fix: Fix caffe dockerfile base image
  build/extract/caffe/Dockerfile
Labels: approved, lgtm, release-note-none, size/XS

#154 chore(*): Update docker image tag
  README.md
  README_zh.md
  manifests/examples/serving/graphdef-sdep.yaml
  manifests/examples/serving/header-diversion-sdep.yaml
  manifests/examples/serving/netdef-sdep.yaml
  manifests/examples/serving/onnx-sdep.yaml
  manifests/examples/serving/pecent-diversion-sdep.yaml
  manifests/examples/serving/pmml-sdep.yaml
  manifests/examples/serving/savedmodel-sdep.yaml
  manifests/examples/serving/tensorrt-sdep.yaml
  manifests/examples/serving/torchscript-sdep.yaml
  manifests/model-registry/values.yaml
Labels: approved, lgtm, release-note-none, size/M
