Repository kleveross/klever-model-registry, pull requests merged in 2020-11, with the labels that each got.

#169 chore(*): Resolve joint debugging problem
  go.mod
  go.sum
  pkg/registry/apis/v1alpha1/descriptors/event.go
  pkg/registry/event/event.go
  pkg/registry/event/event_suite_test.go
  pkg/registry/modeljob/modeljob.go
  pkg/registry/modeljob/util.go
  vendor/k8s.io/apimachinery/pkg/util/cache/expiring.go
Labels: approved, lgtm, release-note-none, size/L

#173 chore(*): Upgrade github action command
  .github/workflows/e2e.yml
  .github/workflows/main.yml
  .github/workflows/publish.yml
Labels: approved, lgtm, release-note, size/S

#174 chore(*): Update caffe Dockerfile
  build/extract/caffe/Dockerfile
Labels: lgtm, release-note, size/XS

#175 chore(*): Update caffe Dockerfile
  build/extract/caffe/Dockerfile
Labels: release-note-none

#179 Fix(mlserver): fix mlserver dockerfile
  build/serving/mlserver/Dockerfile
Labels: approved, lgtm, release-note-none, size/XS

#178 Feat(crd): init model job crd when run the controller
  .github/workflows/e2e.yml
  build/model-registry/Dockerfile
  cmd/modeljob-operator/app/server.go
  crds/kleveross.io_modeljobs.yaml
  pkg/controllers/suite_test.go
Labels: approved, lgtm, release-note-none, size/L

#177 Feat(install): add klever-web in install scripts
  scripts/installation/install.sh
Labels: approved, lgtm, release-note-none, size/XS

#181 feat(*): update build dockerfiles
  .github/workflows/publish.yml
  Makefile
  build/serving/tritonserver/Dockerfile
  manifests/examples/modeljob/modeljobs_v1alpha1_mxnet_extract.yaml
  manifests/examples/serving/graphdef-sdep.yaml
  manifests/examples/serving/header-diversion-sdep.yaml
  manifests/examples/serving/netdef-sdep.yaml
  manifests/examples/serving/onnx-sdep.yaml
  manifests/examples/serving/pecent-diversion-sdep.yaml
  manifests/examples/serving/savedmodel-sdep.yaml
  manifests/examples/serving/tensorrt-sdep.yaml
  manifests/examples/serving/torchscript-sdep.yaml
  manifests/model-registry/values.yaml
  manifests/modeljob-operator/templates/preset-image-configmap.yaml
  pkg/registry/serving/composer.go
  pkg/registry/serving/composer_test.go
Labels: approved, lgtm, release-note-none, size/L

#182 Fix(Dockerfile): fix operator and registry dockerfile to add crd file in image
  build/model-registry/Dockerfile
  build/modeljob-operator/Dockerfile
Labels: approved, lgtm, release-note-none, size/XS

#185 chore(*): update modeljob operator helm
  manifests/modeljob-operator/templates/preset-image-configmap.yaml
  manifests/modeljob-operator/values.yaml
Labels: approved, lgtm, release-note, size/M

#171 fix(serving):fix bug of create and update api of serving
  pkg/registry/apis/v1alpha1/descriptors/serving.go
  pkg/registry/serving/composer.go
  pkg/registry/serving/serving.go
  testutil/integration/serving_test.go
Labels: approved, lgtm, release-note, size/L

#188 fix(scripts): fix install scripts
  manifests/modeljob-operator/templates/preset-image-configmap.yaml
  manifests/modeljob-operator/values.yaml
  scripts/installation/install.sh
  scripts/installation/patch/harbor-helm/templates/core/core-dpl.yaml
Labels: release-note, size/L

#180 feat(extract):update model extract
  Makefile
  build/extract/caffe/Dockerfile
  build/extract/caffe2/Dockerfile
  build/extract/graphdef/Dockerfile
  build/extract/h5/Dockerfile
  build/extract/mxnetparams/Dockerfile
  build/extract/onnx/Dockerfile
  build/extract/pmml/Dockerfile
  build/extract/savedmodel/Dockerfile
  build/extract/tensorrt/Dockerfile
  build/extract/torchscript/Dockerfile
  build/nvcaffe-cpu/Dockerfile
  pkg/controllers/utils.go
  scripts/convert/caffe/__init__.py
  scripts/convert/caffe/proto/.ipynb_checkpoints/caffe_pb2-checkpoint.py
  scripts/convert/caffe/proto/__init__.py
  scripts/convert/caffe/proto/caffe_pb2.py
  scripts/extract/README.md
  scripts/extract/extract.py
  scripts/extract/extractor/__init__.py
  scripts/extract/extractor/base_extract.py
  scripts/extract/extractor/extract_caffe.py
  scripts/extract/extractor/extract_caffe2.py
  scripts/extract/extractor/extract_onnx.py
  scripts/extract/extractor/extract_pmml.py
  scripts/extract/extractor/extract_savedmodel.py
  scripts/extract/extractor/extract_tensorrt.py
Labels: approved, lgtm, release-note, size/XXL
