Repository kleveross/klever-model-registry, pull requests merged in 2020-10, with the labels that each got.

#156 feat(serving): Upgrade triton server to v20.08
  build/serving/tensorrt/Dockerfile
  pkg/registry/serving/composer.go
  scripts/serving/tensorrt/entrypoint.sh
Labels: approved, lgtm, release-note-none, size/S

#158 feat (KLV-11): HPA support via seldonDeployment update
  docs/README.md
  docs/docs_zh/README.md
  pkg/registry/apis/v1alpha1/descriptors/serving.go
  pkg/registry/serving/serving.go
  testutil/integration/serving_test.go
Labels: approved, lgtm, release-note-none, size/M

#159 feat(serving): Support custom image
  pkg/registry/serving/composer.go
  pkg/registry/serving/composer_test.go
Labels: approved, lgtm, release-note-none, size/L

#161 chore(*): use service.WrapHTTPHandler in proxy APIs
  go.mod
  go.sum
  pkg/registry/apis/v1alpha1/descriptors/harbor.go
  vendor/github.com/caicloud/nirvana/definition/definition.go
  vendor/github.com/caicloud/nirvana/log/log.go
  vendor/github.com/caicloud/nirvana/service/builder.go
  vendor/github.com/caicloud/nirvana/service/context.go
  vendor/github.com/caicloud/nirvana/service/executor.go
  vendor/github.com/caicloud/nirvana/service/utils.go
  vendor/github.com/caicloud/nirvana/utils/api/definitions.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L

#162 Fix(scripts): fix python lint
  scripts/serving/wrapper/preprocessor.py
  scripts/serving/wrapper/utils/config_generator.py
  scripts/serving/wrapper/utils/get_model.py
  scripts/serving/wrapper/utils/help_functions.py
  scripts/serving/wrapper/utils/model_formatter.py
Labels: approved, lgtm, release-note-none, size/M

#160 feat(KLV-30): add mlflow support for model registry
  README.md
  README_zh.md
  docs/docs_zh/README.md
  docs/installation.md
  manifests/model-registry/templates/deployment.yaml
  manifests/model-registry/templates/serviceaccount.yaml
  manifests/model-registry/values.yaml
  manifests/modeljob-operator/templates/deployment.yaml
  manifests/modeljob-operator/templates/secret.yaml
  pkg/apis/modeljob/v1alpha1/modeljob_types.go
  pkg/controllers/utils.go
  pkg/registry/modeljob/util.go
  pkg/registry/serving/composer.go
  scripts/installation/install.sh
  scripts/serving/wrapper/preprocessor.py
Labels: approved, kind/feature, lgtm, release-note-none, size/L

#163 Feat(serving): add spark mllib model serving
  build/serving/mlserver/Dockerfile
  pkg/apis/modeljob/v1alpha1/modeljob_types.go
  pkg/registry/serving/composer.go
  scripts/serving/mlserver/entrypoint.sh
  scripts/serving/wrapper/preprocessor.py
  scripts/serving/wrapper/utils/help_functions.py
  scripts/serving/wrapper/utils/model_formatter.py
Labels: approved, lgtm, release-note-none, size/L

#164 Fix(serving): fix create serving bug
  manifests/model-registry/values.yaml
  pkg/registry/serving/composer.go
  pkg/registry/serving/composer_test.go
Labels: approved, lgtm, release-note-none, size/S

#166 feat: Add get pod instance
  cmd/model-registry/main.go
  pkg/registry/apis/v1alpha1/descriptors/pod.go
  pkg/registry/pod/pod.go
Labels: approved, lgtm, release-note-none, size/M

#167 chore(*): Solve some issue by docking with the frontend
  manifests/modeljob-operator/templates/cluster-role.yaml
  pkg/controllers/reconcile.go
  pkg/registry/apis/v1alpha1/descriptors/event.go
  pkg/registry/apis/v1alpha1/descriptors/modeljob.go
  pkg/registry/event/event.go
  pkg/registry/event/event_test.go
  pkg/registry/harbor/harbor.go
  pkg/registry/modeljob/modeljob.go
  pkg/registry/modeljob/modeljob_test.go
  pkg/registry/modeljob/util.go
Labels: approved, lgtm, release-note-none, size/L
