Repository kleveross/klever-model-registry, pull requests merged in 2020-08, with the labels that each got.

#68 feat: Using cache to list/get resource
  cmd/klever-model-registry/main.go
  go.mod
  go.sum
  pkg/apis/modeljob/v1alpha1/modeljob_types.go
  pkg/common/consts.go
  pkg/controllers/initialization.go
  pkg/controllers/utils_test.go
  pkg/registry/apis/v1alpha1/descriptors/event.go
  pkg/registry/apis/v1alpha1/descriptors/log.go
  pkg/registry/apis/v1alpha1/descriptors/modeljob.go
  pkg/registry/client/client.go
  pkg/registry/event/event.go
  pkg/registry/event/event_suite_test.go
  pkg/registry/event/event_test.go
  pkg/registry/log/log.go
  pkg/registry/modeljob/modeljob.go
  pkg/registry/modeljob/modeljob_suite_test.go
  pkg/registry/modeljob/modeljob_test.go
  pkg/registry/models/files.go
Labels: approved, lgtm, release-note-none, size/L

#69 feat: Using ormb-storage-initializer
  manifests/klever-modeljob-operator/templates/preset-image-configmap.yaml
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
  scripts/shell/run.sh
  testutil/testutil.go
Labels: approved, lgtm, release-note-none, size/L

#70 feat: Unified error code format
  pkg/registry/errors/errors.go
  pkg/registry/event/event.go
  pkg/registry/log/log.go
  pkg/registry/modeljob/modeljob.go
  pkg/registry/models/files.go
Labels: approved, lgtm, release-note-none, size/L

#71 feat: Set relayout false for ormb-storage-initializer
  pkg/controllers/utils.go
Labels: approved, lgtm, release-note-none, size/XS

#72 feat: support tensorrt extract
  build/extract/tensorrt/Dockerfile
  scripts/extract/extractor/__init__.py
  scripts/extract/extractor/extract_tensorrt.py
Labels: approved, lgtm, release-note-none, size/M

#74 docs: Add ui mockup
  README.md
  README_zh.md
  docs/images/conversion.png
  docs/images/model.png
Labels: approved, lgtm, release-note-none, size/S

#73 misc: Optimize the code
  .gitignore
  Makefile
  cmd/klever-model-registry/main.go
  go.mod
  pkg/registry/apis/api.go
  pkg/registry/apis/v1alpha1/descriptors/harbor.go
  pkg/registry/client/client.go
  pkg/registry/config/types.go
  pkg/registry/harbor/harbor.go
  pkg/registry/models/util_test.go
Labels: approved, lgtm, release-note-none, size/L

#76 feat: Use github actions to run ut and e2e test
  .github/workflows/main.yml
Labels: release-note-none, size/M

#77 fix: Fix CI using GitHub Actions
  .github/workflows/main.yml
  README.md
Labels: release-note-none, size/M

#75 feat: Support simple model serving
  Makefile
  build/model-registry/Dockerfile
  build/modeljob-operator/Dockerfile
  cmd/model-registry/main.go
  cmd/modeljob-operator/app/options/options.go
  cmd/modeljob-operator/app/server.go
  cmd/modeljob-operator/main.go
  go.sum
  manifests/examples/modeljobs_v1alpha1_savedmodel_extract.yaml
  manifests/klever-modeljob-operator/templates/cluster-role.yaml
  manifests/model-registry/.helmignore
  manifests/model-registry/Chart.yaml
  manifests/model-registry/templates/NOTES.txt
  manifests/model-registry/templates/_helpers.tpl
  manifests/model-registry/templates/deployment.yaml
  manifests/model-registry/templates/kleveross-gateway.yaml
  manifests/model-registry/templates/service.yaml
  manifests/model-registry/values.yaml
  manifests/modeljob-operator/.helmignore
  manifests/modeljob-operator/Chart.yaml
  manifests/modeljob-operator/crds/kleveross.io_modeljobs.yaml
  manifests/modeljob-operator/templates/NOTES.txt
  manifests/modeljob-operator/templates/_helpers.tpl
  manifests/modeljob-operator/templates/cluster-role-binding.yaml
  manifests/modeljob-operator/templates/cluster-role.yaml
  manifests/modeljob-operator/templates/deployment.yaml
  manifests/modeljob-operator/templates/preset-image-configmap.yaml
  manifests/modeljob-operator/templates/secret.yaml
  manifests/modeljob-operator/values.yaml
  pkg/common/consts.go
  pkg/controllers/suite_test.go
  pkg/controllers/utils.go
  pkg/registry/apis/v1alpha1/descriptors/serving.go
  pkg/registry/serving/composer.go
  pkg/registry/serving/serving.go
  scripts/serving/openscoring/docker/Dockerfile
  scripts/serving/openscoring/docker/application.conf
  scripts/serving/tensorrt/docker/Dockerfile
  scripts/serving/tensorrt/docker/requirements.txt
  scripts/serving/wrapper/.pylintrc
  scripts/serving/wrapper/entrypoint.sh
  scripts/serving/wrapper/openscoring.sh
  scripts/serving/wrapper/preprocessor.py
  scripts/serving/wrapper/utils/__init__.py
  scripts/serving/wrapper/utils/config_generator.py
  scripts/serving/wrapper/utils/get_model.py
  scripts/serving/wrapper/utils/help_functions.py
  scripts/serving/wrapper/utils/model_formatter.py
  scripts/shell/run.sh
Labels: approved, lgtm, release-note-none, size/XXL

#82 feat: Support inference's traffic diversion
  pkg/registry/serving/composer.go
Labels: approved, lgtm, release-note-none, size/M

#83 feat: Add serving unittest
  pkg/registry/serving/composer_test.go
  pkg/registry/serving/serving.go
  pkg/registry/serving/serving_suite_test.go
Labels: approved, lgtm, release-note-none, size/L

#84 feat: Support GPU scheduling
  pkg/registry/serving/composer.go
Labels: approved, lgtm, release-note-none, size/S
