Repository kleveross/klever-model-registry, pull requests merged in 2020-12, with the labels that each got.

#190 chore(*): update github template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, release-note, size/M

#193 fix(serving): fix serving model uri params
  pkg/controllers/utils.go
  pkg/registry/serving/composer.go
  pkg/registry/serving/composer_test.go
  pkg/registry/serving/serving_suite_test.go
Labels: approved, area/serving, kind/bug, lgtm, release-note, size/M

#195 chore(*): upgrade ormb to v0.0.8
  Makefile
  go.mod
  go.sum
  manifests/examples/serving/graphdef-sdep.yaml
  manifests/examples/serving/header-diversion-sdep.yaml
  manifests/examples/serving/netdef-sdep.yaml
  manifests/examples/serving/onnx-sdep.yaml
  manifests/examples/serving/pecent-diversion-sdep.yaml
  manifests/examples/serving/pmml-sdep.yaml
  manifests/examples/serving/savedmodel-sdep.yaml
  manifests/examples/serving/tensorrt-sdep.yaml
  manifests/examples/serving/torchscript-sdep.yaml
  manifests/modeljob-operator/values.yaml
  vendor/github.com/kleveross/ormb/LICENSE
  vendor/github.com/kleveross/ormb/pkg/model/format.go
  vendor/github.com/kleveross/ormb/pkg/model/types.go
  vendor/github.com/kleveross/ormb/pkg/ormb/ormb.go
  vendor/modules.txt
Labels: approved, area/model, kind/upgrade, lgtm, release-note, size/L

#194 fix(build): fix caffe build
  Makefile
Labels: approved, kind/bug, lgtm, release-note-none, size/S

#196 feat(operator): support env for operator
  pkg/apis/modeljob/v1alpha1/modeljob_types.go
  pkg/apis/modeljob/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/consts.go
  pkg/controllers/utils.go
Labels: approved, area/model, kind/feature, lgtm, release-note, size/M

#197 feat(*):update signature
  scripts/extract/extractor/extract_caffe.py
  scripts/extract/extractor/extract_graphdef.py
  scripts/extract/extractor/extract_keras.py
  scripts/extract/extractor/extract_mxnet.py
  scripts/extract/extractor/extract_onnx.py
  scripts/extract/extractor/extract_pmml.py
  scripts/extract/extractor/extract_savedmodel.py
  scripts/extract/extractor/extract_tensorrt.py
  scripts/extract/extractor/extract_torchscript.py
  scripts/serving/wrapper/preprocessor.py
  scripts/serving/wrapper/utils/config_generator.py
Labels: approved, lgtm, release-note, size/L

#198 feat(*): support convert read inputs from env
  scripts/convert/converter/base_convert.py
Labels: approved, area/model, kind/feature, lgtm, release-note, size/S

#199 fix(controller): fix image tag & some consts
  manifests/modeljob-operator/values.yaml
  pkg/controllers/consts.go
Labels: approved, area/model, kind/bug, lgtm, release-note, size/XS

#201 fix(convert): fix caffe extract scripts bugs
  build/convert/caffemodel_to_netdef/Dockerfile
  scripts/convert/converter/base_convert.py
Labels: approved, area/model, kind/bug, lgtm, release-note-none, size/S

#200 feat(scripts): support env for scripts
  scripts/convert/converter/base_convert.py
  scripts/serving/wrapper/preprocessor.py
Labels: approved, area/model, area/serving, kind/feature, lgtm, release-note, size/M

#202 chore(*): update netdef dir & path
  Makefile
  build/extract/caffemodel/Dockerfile
  build/extract/netdef/Dockerfile
  manifests/modeljob-operator/values.yaml
Labels: approved, area/model, kind/bug, lgtm, release-note, size/XS

#205 fix(converter): dockerfile and add check for input
  build/convert/caffemodel_to_netdef/Dockerfile
  scripts/convert/converter/__init__.py
  scripts/convert/converter/base_convert.py
Labels: approved, area/model, kind/bug, lgtm, release-note-none, size/S

#206 fix(job): inject env to job
  pkg/controllers/utils.go
Labels: approved, area/model, kind/bug, lgtm, release-note, size/XS

#204 Fix(image): get convert and extract image from env
  manifests/modeljob-operator/templates/deployment.yaml
  manifests/modeljob-operator/templates/preset-image-configmap.yaml
  manifests/modeljob-operator/values.yaml
  pkg/controllers/consts.go
  pkg/controllers/initialization.go
  pkg/controllers/modeljob_controller_test.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
  testutil/testutil.go
Labels: approved, area/serving, kind/deprecation, lgtm, release-note, size/L

#207 Fix(env): fix env name in model job deployment
  manifests/modeljob-operator/templates/deployment.yaml
Labels: approved, area/serving, kind/bug, lgtm, release-note, size/XS

#203 test(E2ETest): Add e2e test cases for serving
  testutil/integration/serving_test.go
Labels: approved, area/serving, kind/test, lgtm, release-note, size/M

#208 chore(doc): update README
  README.md
  README_zh.md
  scripts/installation/install-k8s-1.19.sh
Labels: approved, kind/documentation, lgtm, release-note, size/S

#209 feat(test): add model extract/convert e2e test
  .github/workflows/publish.yml
  Makefile
  build/convert/caffemodel_to_netdef/Dockerfile
  build/convert/h5_to_savedmodel/Dockerfile
  build/convert/mxnetparams_to_onnx/Dockerfile
  build/convert/netdef_to_onnx/Dockerfile
  build/extract/caffemodel/Dockerfile
  build/extract/graphdef/Dockerfile
  build/extract/h5/Dockerfile
  build/extract/mxnetparams/Dockerfile
  build/extract/netdef/Dockerfile
  build/extract/onnx/Dockerfile
  build/extract/pmml/Dockerfile
  build/extract/savedmodel/Dockerfile
  build/extract/tensorrt/Dockerfile
  build/extract/torchscript/Dockerfile
  scripts/shell/test.sh
Labels: approved, area/model, kind/test, lgtm, release-note, size/L

#210 fix(test): update yaml pkg && caffe2 model path
  scripts/convert/converter/base_convert.py
  scripts/extract/extract.py
  scripts/shell/test.sh
Labels: approved, area/cicd, kind/bug, lgtm, release-note, size/S

#212 fix(serving):fix bug of container's volumes and volumeMounts cannot be covered
  pkg/registry/serving/composer.go
Labels: approved, area/serving, kind/bug, lgtm, release-note, size/S

#214 feat(vendor):update vendor to kubernetes v1.19.3
  go.mod
  go.sum
  vendor/k8s.io/api/apps/v1beta1/types.go
  vendor/k8s.io/api/apps/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/apps/v1beta2/types.go
  vendor/k8s.io/api/apps/v1beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/api/extensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/modules.txt
Labels: approved, area/serving, kind/feature, lgtm, release-note, size/L

#215 feat(serving): must ensure that all subpaths of volumemount use the default rule
  pkg/registry/serving/composer.go
Labels: approved, area/serving, kind/feature, lgtm, release-note-none, size/S

#216 Feat(compose): skip compose init container when users have one
  pkg/registry/serving/composer.go
Labels: approved, kind/feature, lgtm, release-note, size/XS

#218 fix(extract):graphdef dtype key error
  scripts/extract/extractor/extract_graphdef.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#220 fix(serving):fix bug of modelDir's name must be "model"
  scripts/serving/wrapper/preprocessor.py
Labels: approved, area/serving, kind/bug, lgtm, release-note, size/S

#219 fix(scripts): fix graphdef formater
  scripts/serving/wrapper/utils/model_formatter.py
Labels: approved, area/model, kind/bug, lgtm, release-note, size/XS

#217 feat(crd): add init container in crd
  crds/kleveross.io_modeljobs.yaml
  pkg/apis/modeljob/v1alpha1/modeljob_types.go
  pkg/apis/modeljob/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/modeljob/v1alpha1/zz_generated.defaults.go
  pkg/clientset/clientset/versioned/clientset.go
  pkg/clientset/clientset/versioned/doc.go
  pkg/clientset/clientset/versioned/fake/clientset_generated.go
  pkg/clientset/clientset/versioned/fake/doc.go
  pkg/clientset/clientset/versioned/fake/register.go
  pkg/clientset/clientset/versioned/scheme/doc.go
  pkg/clientset/clientset/versioned/scheme/register.go
  pkg/clientset/clientset/versioned/typed/modeljob/v1alpha1/doc.go
  pkg/clientset/clientset/versioned/typed/modeljob/v1alpha1/fake/doc.go
  pkg/clientset/clientset/versioned/typed/modeljob/v1alpha1/fake/fake_modeljob.go
  pkg/clientset/clientset/versioned/typed/modeljob/v1alpha1/fake/fake_modeljob_client.go
  pkg/clientset/clientset/versioned/typed/modeljob/v1alpha1/generated_expansion.go
  pkg/clientset/clientset/versioned/typed/modeljob/v1alpha1/modeljob.go
  pkg/clientset/clientset/versioned/typed/modeljob/v1alpha1/modeljob_client.go
  pkg/clientset/informers/externalversions/factory.go
  pkg/clientset/informers/externalversions/generic.go
  pkg/clientset/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/clientset/informers/externalversions/modeljob/interface.go
  pkg/clientset/informers/externalversions/modeljob/v1alpha1/interface.go
  pkg/clientset/informers/externalversions/modeljob/v1alpha1/modeljob.go
  pkg/clientset/listers/modeljob/v1alpha1/expansion_generated.go
  pkg/clientset/listers/modeljob/v1alpha1/modeljob.go
  pkg/controllers/utils.go
  pkg/registry/comparison/testFile
  pkg/registry/harbor/artifacts.go
  pkg/registry/modeljob/modeljob.go
  pkg/registry/models/files.go
Labels: approved, kind/documentation, lgtm, release-note, size/XXL

#222 refactor(controller): refactor event & log
  pkg/controllers/consts.go
  pkg/controllers/reconcile.go
  pkg/controllers/utils.go
Labels: approved, area/model, lgtm, release-note, size/M

#223 fix(scripts): remove echo password
  scripts/shell/run.sh
Labels: approved, area/model, kind/cleanup, lgtm, release-note, size/XS

#224 fix(crds): update crds path
  Makefile
  manifests/modeljob-operator/crds/kleveross.io_modeljobs.yaml
Labels: approved, area/serving, kind/bug, lgtm, release-note, size/XXL

#225 feat(doc): update doc
  README.md
  README_zh.md
  docs/README.md
  docs/docs_zh/README.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS
