Repository kleveross/klever-model-registry, pull requests merged in 2021-01, with the labels that each got.

#226 fix(savedmodel): inputs/outputs name in signature
  scripts/extract/extractor/extract_savedmodel.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#227 feat(vendor): update vendor
  go.mod
  go.sum
  vendor/github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  vendor/github.com/seldonio/seldon-core/operator/constants/constants.go
  vendor/modules.txt
Labels: approved, area/serving, kind/feature, lgtm, release-note-none, size/M

#228 feat(operator): add error message detail
  pkg/controllers/consts.go
  pkg/controllers/reconcile.go
  pkg/controllers/reconcile_test.go
Labels: approved, area/model, kind/feature, lgtm, release-note, size/L

#230 chore(*): upgrade ormb to v0.0.10
  Makefile
Labels: approved, kind/feature, lgtm, release-note, size/XS

#231 feat(release): release v0.3.0-alpha.2
  manifests/model-registry/Chart.yaml
  manifests/model-registry/values.yaml
  manifests/modeljob-operator/Chart.yaml
  manifests/modeljob-operator/values.yaml
Labels: approved, lgtm, release-note, size/M

#232 fix(serving): fix bug of remove old folder when restart serving's pod
  scripts/serving/wrapper/preprocessor.py
Labels: approved, area/serving, kind/bug, lgtm, release-note, size/XS

#233 refactor(controller): refactor error message
  pkg/controllers/consts.go
  pkg/controllers/reconcile.go
  pkg/controllers/reconcile_test.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#234 fix(model): fix modeljob status
  pkg/controllers/reconcile.go
Labels: approved, kind/bug, lgtm, release-note-none, size/S

#236 fix(serving): cancel determine whether ormbfile.yaml file and model folder exist
  scripts/serving/wrapper/preprocessor.py
Labels: approved, area/serving, kind/bug, lgtm, release-note, size/S

#235 feat(triton): update v20.08 to v20.09
  build/serving/tritonserver/Dockerfile
Labels: approved, area/serving, kind/upgrade, lgtm, release-note, size/XS

#237 fix(serving): fix bug of serving userContainer's image and env
  pkg/registry/serving/composer.go
  scripts/serving/wrapper/preprocessor.py
Labels: approved, area/serving, kind/bug, lgtm, release-note, size/S

#238 chore(release): release v0.3.0-rc.1
  Makefile
  go.mod
  go.sum
  manifests/model-registry/Chart.yaml
  manifests/model-registry/values.yaml
  manifests/modeljob-operator/Chart.yaml
  manifests/modeljob-operator/values.yaml
  vendor/github.com/kleveross/ormb/pkg/model/format.go
  vendor/github.com/kleveross/ormb/pkg/model/types.go
  vendor/github.com/kleveross/ormb/pkg/oras/client.go
  vendor/github.com/kleveross/ormb/pkg/oras/interface.go
  vendor/github.com/kleveross/ormb/pkg/ormb/mock/mock_ormb.go
  vendor/github.com/kleveross/ormb/pkg/ormb/ormb.go
  vendor/github.com/kleveross/ormb/pkg/saver/saver.go
  vendor/github.com/kleveross/ormb/pkg/util/bytes/byte.go
  vendor/github.com/kleveross/ormb/pkg/util/util.go
  vendor/github.com/xeonx/timeago/.travis.yml
  vendor/github.com/xeonx/timeago/LICENSE
  vendor/github.com/xeonx/timeago/README.md
  vendor/github.com/xeonx/timeago/timeago.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XL

#239 fix(scripts): do not set signature for conversion
  scripts/convert/converter/base_convert.py
Labels: approved, area/model, kind/bug, lgtm, release-note-none, size/XS
